---
- name: Hi K
  hosts: localhost
  tasks:
  - include_vars: ./newservicedetails.yml
  - name: create new service
    uri:
      url: "{{url}}"
      method: "{{verb}}"
      body: "access_token={{access_token}}&name={{name}}&deployment_option={{deployment_option}}&backend_version={{backend_version}}&system_name={{system_name}}"
      validate_certs: false
      return_content: yes
      status_code: "{{status_code}}"
    register: result
  - name: Find the project id
    set_fact:
      newserviceid: "{{result.json.service.id }}"
  - debug:
      msg: "{{result.json.service.id}}"

  - include_vars: ./updateservicedetails.yml
  - name: update backend production and staging urls
    uri:
      url: "{{url}}/{{newserviceid}}/proxy.xml"
      method: "{{verb}}"
      body: "access_token={{access_token}}&name={{name}}&api_backend={{api_backend}}&endpoint={{endpoint}}&sandbox_endpoint={{sandbox}}"
      validate_certs: false
      return_content: yes
      status_code: "{{status_code}}"

  - name: get default metric id ..change later to create a new metric and new method
    uri:
      url: "{{url}}/{{newserviceid}}/metrics.json"
      validate_certs: false
      method: GET
      body: "access_token={{access_token}}"
      return_content: yes
      status_code: 200
    register: metricid

  - debug:
      msg: "{{metricid.json.metrics[0].metric.id}}"

  - name: create a mapping rule
    uri:
      url: "{{url}}/{{newserviceid}}/proxy/mapping_rules.xml"
      method: POST
      body: "access_token={{access_token}}&http_method={{http_method}}&pattern={{pattern}}&delta={{delta}}&metric_id={{metricid.json.metrics[0].metric.id}}"
      validate_certs: false
      return_content: yes
      status_code: 201
  - name: create an application plan
    uri:
      url: "{{url}}/{{newserviceid}}/application_plans.json"
      method: POST
      body: "access_token={{access_token}}&name={{applicationplanname}}n&system_name={{applicationplansystemname}}"
      validate_certs: false
      return_content: yes
      status_code: 201
      #body_format: json
    register: result
  - name: Find the project id
    set_fact:
      example_plan_id: "{{result.json.application_plan.id }}"

  - name: create a test application
    uri:
      url: "{{basedomain}}/admin/api/accounts/{{accountid}}/applications.xml"
      method: POST
      body: "access_token={{access_token}}&plan_id={{example_plan_id}}&name={{applicationname}}&description={{applicationdescription}}+cd&user_key={{user_key}}"
      validate_certs: false
      return_content: yes
      status_code: 201

  - name: sleep for 100 seconds and continue with play
    wait_for: timeout=100

  - name: quick test
    uri:
      url: "{{sandbox}}/customer?user_key={{user_key}}"
      validate_certs: false
      method: GET
      return_content: yes
      status_code: 200 
    register: finalresult

  - debug:
      msg: "{{finalresult}}"
